name: Test Checkout Action

on: push

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Dump Github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: After Checkout
      run: |
        cat README.md
        echo "test" > test.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "commit from action"
        git push origin checkout-action


