name: Action on tag

on:
  push:
    tags:
      - "**.*.*"
    branches: on-tag

jobs:
  test-tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Got Tagged
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
        echo "$GITHUB_CONTEXT"
        echo "Just ref"
        echo "$GITHUB_CONTEXT.ref"