name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node_version: [6,8,10] # will run 3 times. 1 with each version
        include: # include adds an extra variable to items already included in matrix
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: windows-latest
            node_version: 8
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }} # can access matrix inside strategy node
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_8