name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node_version: [6,8,10] # will run 3 times. 1 with each version
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }} # can access matrix inside strategy node
      - name: Log node version
        run: node -v